services:
  database:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hurribrain
      MYSQL_USER: neuron
      MYSQL_PASSWORD: synapse
    ports:
      - "3306:3306"
    container_name: hurribrain-mysql
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: hurribrain-redis

volumes:
  mysql_data:
